name: Build Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
          - 1.17
          - 1.18
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: check fmt
        run: find . -name '*.go' | xargs gofmt -l | read && echo "Code differs from gofmt's style. Run 'gofmt -w .'" 1>&2 && exit 1 || true

      - name: check go.mod
        shell: bash
        run: |
          go mod tidy
          git diff-index --quiet HEAD

      - name: go test
        run: go test ./...

      -
        name: cross build with goreleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot